### ISSUE TITLE
Error when trying to execute rake tasks

### ISSUE THREAD

**Issue by juliobetta** [NREL/osw2osa#2]
* Ruby v2.5.5

I'm getting the following error when I try to run any rake tasks:

```
bundle exec rake -T
```

```
rake aborted!
LoadError: cannot load such file -- openstudio
/Volumes/Projects/osw2osa/Rakefile:6:in `require'
/Volumes/Projects/osw2osa/Rakefile:6:in `<top (required)>'
/Volumes/Projects/osw2osa/.bundle/install/ruby/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/juliobetta/.asdf/installs/ruby/2.5.5/bin/bundle:23:in `load'
/Users/juliobetta/.asdf/installs/ruby/2.5.5/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

I tried to include the `openstudio` gem into the Gemfile, but I'm getting this error:

```
rake aborted!
LoadError: cannot load such file -- openstudioutilitiescore
/Volumes/Projects/osw2osa/.bundle/install/ruby/2.5.0/gems/openstudio-0.7.6/lib/openstudio.rb:46:in `require'
/Volumes/Projects/osw2osa/.bundle/install/ruby/2.5.0/gems/openstudio-0.7.6/lib/openstudio.rb:46:in `<top (required)>'
/Volumes/Projects/osw2osa/Rakefile:6:in `require'
/Volumes/Projects/osw2osa/Rakefile:6:in `<top (required)>'
/Volumes/Projects/osw2osa/.bundle/install/ruby/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/juliobetta/.asdf/installs/ruby/2.5.0/bin/bundle:23:in `load'
/Users/juliobetta/.asdf/installs/ruby/2.5.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

My next move was including `openstudioutilitiescore` into the Gemfile, but that's not a gem 😅 

I'm sure I'm missing something...

**Comment by juliobettamaalka** [comment]
I restarted my terminal and everything just worked... 🤦

**Comment by juliobetta** [comment]
I restarted my terminal and everything just worked... 🤦
